name: your_plan
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.7  

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_svg: ^2.0.7
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/icon/arrow_right.svg

